import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { signIn, signOut, useSession } from 'next-auth/client';

export default function Home() {
  const [session, loading] = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!session && (
          <>
            Not signed in <br />
            <button className={styles.button} onClick={() => signIn('cognito')}>
              Sign in
            </button>
          </>
        )}
        {session && (
          <>
            Signed in as {session.user?.email} <br />
            <button className={styles.button} onClick={() => signOut()}>
              Sign out
            </button>
          </>
        )}
      </main>
    </div>
  );
}
